version: "3.1" 
services:
  wbeep_processor:
    image: code.chs.usgs.gov:5001/wma/iidd/wbeep-data-processing:R-latest
    build:
      context: .
    ports:
      - "8787:8787"
    volumes:
      - data:/home/rstudio/wbeep-processing                                                                                              
    environment:
      - ROOT=TRUE
      - PASSWORD=mypass

volumes:
  data:

