version: "3.1" 
services:
  wbeep_processor_tippecanoe:
    image: code.chs.usgs.gov:5001/wma/iidd/wbeep-data-processing:tippecanoe-latest
    build:
      context: .
    ports:
      - "8787:8787"
    volumes:
      - data:/home/wbeep-processing    
    environment:
      - ROOT=TRUE   
    tty: TRUE  
    stdin_open: TRUE
 
volumes:
  data:

